### ISSUE TITLE
Fix thirtythreeforty/xkcd-Bucket

### ISSUE THREAD

**Issue by thirtythreeforty** [QualityEnforcer/QualityEnforcerBot#24]
Please clean this repo up, QualityEnforcerBot.

**Comment by ddevault** [comment]
It's been 3 months since it last fixed up a repo. I checked, and it's still online, but no promises about its performance. We'll see if it picks this up.

**Comment by thirtythreeforty** [comment]
Heh, sounds good!

**Comment by ddevault** [comment]
Yeah, it's not working. I'll figure out why tomorrow, I'm a bit busy at the moment.

**Comment by thirtythreeforty** [comment]
No big deal.  I was mainly playing with it anyway.
